name: Test and Test if deployment works
on:
  push:
  workflow_dispatch:
  
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-heroku
      url: https://dev-capstone-backend.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target
      - name: Login to Heroku
        run: heroku login
      - name: Push docker container
        run: heroku container:push web -a dev-capstone-backend
      - name: Deploy docker container
        run: heroku container:release web -a dev-capstone-backend
      - name: Connect to postgres DB
        run: heroku pg:psql postgresql-vertical-61863 --app dev-capstone-backend
