name: Test and Test if deployment works
on:
  push:
  workflow_dispatch:
  
jobs:
  try-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        env:
          GITHUB_CLIENT_ID: ${{ secrets.MY_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.MY_GITHUB_CLIENT_SECRET }}
        with:
          java-version: '17'
          distribution: 'adopt'
      #- name: Test with Maven
      #  run: mvn test
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DargLine="-MY_GITHUB_CLIENT_ID=2e78a31afe900fd1aef7 -MY_GITHUB_CLIENT_SECRET=ee6bf4d225d84f355ad4a7b98220a159a9a67552"
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/app.jar
          
  try-deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: dev-capstone-backend
           heroku_email: ${{ secrets.HEROKU_MAIL }}
           healthcheck: https://dev-capstone-backend.herokuapp.com/health
           checkstring: "Hello there! I'm running."
        env:
           MY_GITHUB_CLIENT_ID: ${{ secrets.MY_GITHUB_CLIENT_ID }}
           HD_RANDOM_DATA: ${{ secrets.MY_GITHUB_CLIENT_SECRET }}
